### ISSUE TITLE
with vertical tabs turned on, saved workspaces are deleted when floorp is closed and opened.

### ISSUE THREAD

**Issue by universish** [flathub/one.ablaze.floorp#104]
with vertical tabs turned on, saved workspaces are deleted when floorp is closed and opened.

**Comment by dominichayesferen** [comment]
This sounds like a potentially upstream bug in Floorp itself.

Just in case it is, https://github.com/Floorp-Projects/Floorp/issues/new/choose

**Comment by typeling1578** [comment]
This seems to be an upstream bug.
It's not appropriate to discuss this here.
