### ISSUE TITLE
when the vertical tab feature is on, pinned tabs are deleted when floorp is closed and opened, the pinned tab is not fixed.

### ISSUE THREAD

**Issue by universish** [flathub/one.ablaze.floorp#105]
when the vertical tab feature is on, pinned tabs are deleted when floorp is closed and opened, the pinned tab is not fixed.

**Comment by dominichayesferen** [comment]
This sounds like a potentially upstream bug in Floorp itself.

Just in case it is, https://github.com/Floorp-Projects/Floorp/issues/new/choose

**Comment by universish** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1491

**Comment by typeling1578** [comment]
This seems to be an upstream bug.
It's not appropriate to discuss this here.
