### ISSUE TITLE
floorp consumes very high CPU if multiple tabs are opened in multiple containers

### ISSUE THREAD

**Issue by universish** [flathub/one.ablaze.floorp#106]
floorp consumes very high CPU if multiple tabs are opened in multiple containers. 
Too many Isolated Web Co tasks running in task manager. floorp does not give tapki, it says wait or close.

**Comment by dominichayesferen** [comment]
This sounds like a potentially upstream bug in Floorp itself.

Just in case it is, https://github.com/Floorp-Projects/Floorp/issues/new/choose

**Comment by universish** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1492

**Comment by typeling1578** [comment]
This seems to be an upstream bug.
It's not appropriate to discuss this here.
