### ISSUE TITLE
There is no free space on the taskbar to click to drag floorp or the floorp window. 

### ISSUE THREAD

**Issue by universish** [flathub/one.ablaze.floorp#107]
when the menu bar is not active there is no free space on the taskbar to click to grab and drag the window, move the window, pin the window to the edges. i have to activate the menu bar feature. i can click on the free space to click on the menu bar and drag and move the window wherever i want, to whichever edge i want or to whichever workspace i want. But the menu bar is very impractical. It takes up space on the screen horizontally, and since my monitor is small, space is very important for me. My operating system is fedora 40 workstation gnome. I have minimize page and hide page in gnome tweaks on the taskbar. So there is no free space in that area. Since there is no free space there is nowhere to drag and click.

**Comment by dominichayesferen** [comment]
This is an upstream issue in Floorp itself.

https://github.com/Floorp-Projects/Floorp/issues/new/choose

**Comment by universish** [comment]
https://github.com/Floorp-Projects/Floorp/issues/1493
