### ISSUE TITLE
Rename/Remove Lightning Branch

### ISSUE THREAD

**Issue by MonsterObserver** [flathub/one.ablaze.floorp#28]
Flathub doesn't officially support branches other than `beta`, which means Software shows the lightning branch by default. It either has to be removed, or you should rename the branch to `beta`. If you remove the branch you can always use another ID.

**Comment by dominichayesferen** [comment]
i guess @typeling1578

**Comment by typeling1578** [comment]
This is being discussed within the team, but it is expected to take some more time to respond.

**Comment by creeper-0910** [comment]
Floorp-lightning is to be removed due to maintenance issues.
