### ISSUE TITLE
Incorrectly labelled license

### ISSUE THREAD

**Issue by burnedout1024** [flathub/one.ablaze.floorp#76]
The Floorp package on Flathub is currently labelled as 'proprietary'. This appears to be incorrect, as Floorp is an open-source project. The license should be updated to reflect the correct open-source license under which Floorp is distributed.

![License section on GNOME Software](https://github.com/flathub/one.ablaze.floorp/assets/170863356/ba8889dc-e1fe-437d-8ab5-38710fb6376d)

![License section on Flathub](https://github.com/flathub/one.ablaze.floorp/assets/170863356/86455118-8560-4bf3-b689-a7a3b0e96cc0)

**Comment by dominichayesferen** [comment]
https://github.com/flathub/one.ablaze.floorp/pull/61#issuecomment-2021541147
