### ISSUE TITLE
Floorp licensed under MPL but flathub page says it's Proprietary 

### ISSUE THREAD

**Issue by Lokawn** [flathub/one.ablaze.floorp#80]
As stated in the title, Floorp public repository states its open source and licensed under MPL, but flathub Page says its proprietary software. Isn't the flathub page wrong?

**Comment by dominichayesferen** [comment]
Read https://github.com/flathub/one.ablaze.floorp/pull/61#issuecomment-2021541147 for more information.

Floorp has a mixture of licenses for its code, so we default to the least permissive of them to not mislead... but AppStream doesn't like it when we choose said license, thus it's set to Proprietary.
