### ISSUE TITLE
Security warning triggers in the Flatpak

### ISSUE THREAD

**Issue by dominichayesferen** [flathub/one.ablaze.floorp#93]
![image](https://github.com/user-attachments/assets/393ac3ca-eb82-48bf-94e0-62fc21bcab63)

This doesn't trigger in Firefox's Flatpak, and afaik there's nothing missing from BaseApp in our manifest... issue with how Floorp's main download is compiled, maybe?

@typeling1578 @creeper-0910

**Comment by creeper-0910** [comment]
Based on the number of reports, it seems to occur only in one part of the environment.

**Comment by creeper-0910** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1909832
Bug.
